### ISSUE TITLE
New API required

### ISSUE THREAD

**Issue by visualDust** [sanyuankexie/KexieSignsystem#9]
直接获取一个人签到时间的API is required.
黄老板快动（不是

**Comment by Therainisme** [comment]
等黄老板验收了

**Comment by visualDust** [comment]
good

**Comment by 1291945816** [comment]
直接获取一个人的签到时间指的是获取它本周的签到时长吗?

**Comment by visualDust** [comment]
是本周截至到最后一次合法签退的签到时间

**Comment by visualDust** [comment]
黄老板快merge pull request (っ °Д °;)っ

**Comment by visualDust** [comment]
给您比个小心心💕（呕

**Comment by Therainisme** [comment]
我也来给您比个小心心💕（呕

**Comment by 1291945816** [comment]
已经部署好了

**Comment by visualDust** [comment]
@Therainisme new API works but not properly. Some specific id may cause the returened value to be 0.0

**Comment by visualDust** [comment]
for example, try to get the time of id 1900300106 when it's online and you will get a response like this : {"code":500,"message":"暂无相应数据","data":null,"allTime":0.0,"currentTime":0.0}
Yet the user of id 1900300106 is surely online....

**Comment by Therainisme** [comment]
学长设计这个系统的时候，是得签退了，才计算入总时长，而不是实时计算时长的。1900300106这个userId，因为本周没有签退，数据库中无本周数据，也就返回了暂无相应数据。

**Comment by visualDust** [comment]
In that case the API should retun value 0.0 outof the documentation. I think uid 1900300106 does have a record of signin behavior although it haven't signout yet...

**Comment by visualDust** [comment]
Or the frontend should check if the user is online but does not have a time record

**Comment by visualDust** [comment]
Which one you think is better? (both im okay)

**Comment by Therainisme** [comment]
Both

**Comment by visualDust** [comment]
grass

**Comment by Therainisme** [comment]
Now we can wait for boss Huang to merge pull request

**Comment by visualDust** [comment]
I see.... now I'm gonna fix the frontend

**Comment by 1291945816** [comment]
@Therainisme @visualDust Merge Completed

**Comment by 1291945816** [comment]
and deployed
